# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AZLiKNJe3EPxKOrYaJbRUEagN-zineTR
"""

import numpy as np
import pandas as pd
import string

comic = pd.read_csv('./sample_data/Webtoon Dataset.csv')

comic

comic.shape

comic.head()

comic.describe()

comic.info()

#selection data
df1 = comic[['Rating', 'Genre', 'Summary']]
df1